-- schema.sql

-- Use PL/pgSQL to safely drop tables only if they exist.
-- This prevents errors on the very first run when the tables don't exist yet.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'user_feedback') THEN
        DROP TABLE user_feedback;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'chat_messages') THEN
        DROP TABLE chat_messages;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'conversations') THEN
        DROP TABLE conversations;
    END IF;
END $$;


-- We will use the "uuid-ossp" extension to generate UUIDs if needed,
-- though our app will generate them. It's good practice to have it available.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- Table 1: conversations
-- Stores a record for each unique chat session.
CREATE TABLE conversations (
    id BIGSERIAL PRIMARY KEY,
    session_id UUID NOT NULL UNIQUE,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE conversations IS 'Represents a single, unique chat session initiated by a user.';
COMMENT ON COLUMN conversations.session_id IS 'Unique ID generated by the client to group all messages in a session.';
COMMENT ON COLUMN conversations.user_agent IS 'Browser/device info of the user for debugging and analytics.';


-- Table 2: chat_messages
-- Stores every single user query and AI response. This is the core table.
CREATE TABLE chat_messages (
    id BIGSERIAL PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    role VARCHAR(10) NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    response_time_ms INTEGER,
    is_unanswered BOOLEAN DEFAULT FALSE,
    api_metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create indexes for faster querying on foreign keys and timestamps,
-- which will be used constantly by the dashboard.
CREATE INDEX idx_chat_messages_conversation_id ON chat_messages(conversation_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at);

COMMENT ON TABLE chat_messages IS 'Logs every message sent by either the user or the assistant.';
COMMENT ON COLUMN chat_messages.conversation_id IS 'Links the message back to its parent conversation.';
COMMENT ON COLUMN chat_messages.response_time_ms IS 'For assistant messages only: Time from sending request to OpenAI to receiving full response.';
COMMENT ON COLUMN chat_messages.is_unanswered IS 'Flag to easily find questions the RAG system could not answer.';
COMMENT ON COLUMN chat_messages.api_metadata IS 'Rich metadata from the OpenAI API call, like token usage for cost analysis.';


-- Table 3: user_feedback
-- Stores explicit user feedback on the quality of assistant responses.
CREATE TABLE user_feedback (
    id BIGSERIAL PRIMARY KEY,
    message_id BIGINT NOT NULL UNIQUE REFERENCES chat_messages(id) ON DELETE CASCADE,
    rating SMALLINT NOT NULL CHECK (rating IN (-1, 1)),
    comment TEXT, -- Optional field for users to provide more detail.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE user_feedback IS 'Captures user feedback (thumbs up/down) for a specific assistant message.';
COMMENT ON COLUMN user_feedback.message_id IS 'Links feedback directly to the assistant message that was rated.';
COMMENT ON COLUMN user_feedback.rating IS 'Simple user satisfaction score: 1 for positive, -1 for negative.';


-- Grant all permissions on these new tables to our application user.
-- This ensures the user we created ('af_user') can actually read and write data.
GRANT ALL ON TABLE conversations TO af_user;
GRANT ALL ON TABLE chat_messages TO af_user;
GRANT ALL ON TABLE user_feedback TO af_user;

-- The 'id' columns use sequences for auto-incrementing. We need to grant usage rights on those too.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO af_user;